### ISSUE TITLE
Support semantic highlighting added in neovim 0.9

### ISSUE THREAD

**Issue by matgd** [savq/melange-nvim#60]
Since neovim 0.9 color schemes can utilize semantic highlighting from LSP.
I'd love to use this theme with that. 

Comparison (take a close look at `input`, `part` parameters colors and `sequence_len` local variable color):

**savq/melange-nvim**
![Screenshot 2023-04-10 at 13 44 40](https://user-images.githubusercontent.com/28411337/230895980-0653d0cb-dd52-4baa-84ff-fce0e81da61f.png)

**folke/tokyonight.nvim**
![Screenshot 2023-04-10 at 13 44 48](https://user-images.githubusercontent.com/28411337/230896050-266f9f3d-cf17-4bdc-8790-951acaced672.png)

**Comment by savq** [comment]
Most lsp highlight groups seem to have sane links, but I'll take a look to see if there's room for improvement.

I'm open to suggestions regarding parameter highlighting. I personally don't think parameters need to be highlighted differently than other identifiers. Maybe use a boldface instead of a different color?

----

For future reference: [`:help lsp-semantic-highlight`](https://neovim.io/doc/user/lsp.html#lsp-semantic-highlight).
