### ISSUE TITLE
Highlight words in visual mode

### ISSUE THREAD

**Issue by 0x7a7a** [savq/melange-nvim#73]
I find the theme color scheme very comfortable and quite appealing. Thank you for your work.!
The issue now is that it's difficult to distinguish the selected content in visual mode. Would it be possible to make some improvements, such as [gruvbox-material](https://github.com/sainnhe/gruvbox-material)
It has a configuration item to choose the highlighting color: `vim.g.gruvbox_material_visual`

**Comment by savq** [comment]
> it's difficult to distinguish the selected content in visual mode

Do you mean its hard to distinguish the selected area from the background? or the selected text from the selected background? (did that made sense? 😅)

>  It has a configuration item to choose the highlighting color: vim.g.gruvbox_material_visual

I've avoided adding configuration options to melange because inevitably someone will want to change another highlight group, so they'll want another flag added.

You can redefine `Visual` directly. In Lua that'd be:
```lua
local group = vim.api.nvim_create_augroup('OverrideMelange', {})
vim.api.nvim_create_autocmd('ColorScheme', {
  pattern = 'melange',
  callback = function()
    vim.api.nvim_set_hl(0, 'Visual', { bg = '#00ffff' }) -- Choose visual bg color
  end,
  group = group,
})
```

This is somewhat boilerplate heavy. Some package managers have wrappers so that you only need to define the `callback`, but the logic is the same.

**Comment by 0x7a7a** [comment]
Thank you for your reply and help,I see what you mean.
I will close this issue, thanks again.
